### PR TITLE
Fix bytestring problems occuring with Python3

### PR DESCRIPTION
**Pull request by jougs**
@lekshmideepu, @Silmathoron: Does this solve the problem?

### CODE REVIEW

**Comment by lekshmideepu** [comment]
@jougs : Thanks for the quick fix. I think ideally it should solve the problem.

**Comment by lekshmideepu** [comment]
@jougs : https://travis-ci.org/lekshmideepu/nest-simulator/jobs/362614048#L1310
PEP8 complaints :-(

**Comment by Silmathoron** [comment]
line 88, remove indent ;)

**Comment by jougs** [comment]
Done. Sorry for the noise.

**Comment by lekshmideepu** [comment]
Great! @jougs Merging now.

**Pull request merged**
